### ISSUE TITLE
Hi, i have a question about the derivation of Theorem 1 in the paper.

### ISSUE THREAD

**Issue by LanXiaoPang613** [byeonghu-na/tdsm#1]
![image](https://github.com/byeonghu-na/tdsm/assets/35187545/e0f82155-51fb-4983-aab1-112a6ccddb83)
Hi, i have a question about the derivation of Theorem 1 in the paper. As shown in the above image, I think the correct derivation should be as shown in the figure below, and according to the following derivation process, we cannot get the result of theory 1.
![image](https://github.com/byeonghu-na/tdsm/assets/35187545/b87f3e39-5660-4da6-98c5-4a45c72b4f69)
looking forward for your reply soon.

**Comment by byeonghu-na** [comment]
Thank you for your interest in our work. The equality from Eq. (13) to Eq. (14) is obtained by multiplying the same quantity, $p_t(x_t|Y=y)$, in both the numerator and the denominator. A detailed line-by-line derivation is given below. Please feel free to contact me if you have any further questions.

![image](https://github.com/byeonghu-na/tdsm/assets/43334491/d2c70bdd-5a1a-432e-b31d-f29382d6a811)
